A quick append mode for already existing hdf5 files
FAIRmat-NFDI/pynxtools pull request #146
Opened 2023-08-23 13:45 UTC by sherjeelshabih

This is in line with what @mkuehbach brought up. I just cooked up some basic draft to share ideas on this. 

One of the questions we had was what to do if we are adding new data to an existing hdf5 path in the file. We decided to offer a simple (y/n) prompt for the overwrite. But this can be discussed. 

If there is anything else you would like to add please feel free to work on this branch or leave comments.

@domna @RubelMozumder @sanbrock @lukaspie

2023-09-19 09:31 UTC, lukaspie commented
I fully support having the possibility to append data. Maybe this could also work nicely with the ideas of Area A that were discussed yesterday, i.e., allowing for appending ELN data individually (e.g., from a python dict)? In any way, the proposed changes lgtm.

Overwriting old data seems a bit more tricky since you wouldn't want to accidentally overwrite existing data (especially if the writing is automated, e.g. during exporting of experimental data), A y/n prompt may be a good compromise.

2023-09-19 10:50 UTC, mkuehbach commented
I am strongly against adding an option to overwrite existent data especially if there is not a rock-solid mechanism in-place which keeps hashes and provenance of each piece of information or groupings of pieces of information.

2023-09-19 11:13 UTC, sherjeelshabih commented
> I am strongly against adding an option to overwrite existent data especially if there is not a rock-solid mechanism in-place which keeps hashes and provenance of each piece of information or groupings of pieces of information.

I understand. But the problem is if a user wants to replace this, do we block them from doing so and ignore the replacing keys for now? So no asking (y/n) and just warning them about it?

They could always go around our code and replace anything they like. in the h5 files. So I feel like giving the user more power to outright replace what they like using our framework is better.

2023-09-19 12:02 UTC, domna commented
> > I am strongly against adding an option to overwrite existent data especially if there is not a rock-solid mechanism in-place which keeps hashes and provenance of each piece of information or groupings of pieces of information.
> 
> I understand. But the problem is if a user wants to replace this, do we block them from doing so and ignore the replacing keys for now? So no asking (y/n) and just warning them about it?
> 
> They could always go around our code and replace anything they like. in the h5 files. So I feel like giving the user more power to outright replace what they like using our framework is better.

Maybe we could do something like the `--i-am-really-sure` flag we have in the nomad cli? Something which you actively need to add, instead of maybe accidentally hitting `y` out of habit?

2023-09-19 12:11 UTC, sherjeelshabih commented
> > > I am strongly against adding an option to overwrite existent data especially if there is not a rock-solid mechanism in-place which keeps hashes and provenance of each piece of information or groupings of pieces of information.
> > 
> > 
> > I understand. But the problem is if a user wants to replace this, do we block them from doing so and ignore the replacing keys for now? So no asking (y/n) and just warning them about it?
> > They could always go around our code and replace anything they like. in the h5 files. So I feel like giving the user more power to outright replace what they like using our framework is better.
> 
> I see the point. People will do it if they really want to. Maybe we could do something like the `--i-am-really-sure` flag we have in the nomad cli? Something which you actively need to add, instead of maybe accidentally hitting `y` out of habit?

I'm on board with that. Do we make it work just like Nomad where the user has to run the program again with this flag or do we let the user type in "I am really sure!". Note I capitalized the "I" and added an exclamation mark there to make for a stronger approval.

2023-09-19 12:34 UTC, RubelMozumder commented
> > > > I am strongly against adding an option to overwrite existent data especially if there is not a rock-solid mechanism in-place which keeps hashes and provenance of each piece of information or groupings of pieces of information.
> > > 
> > > 
> > > I understand. But the problem is if a user wants to replace this, do we block them from doing so and ignore the replacing keys for now? So no asking (y/n) and just warning them about it?
> > > They could always go around our code and replace anything they like. in the h5 files. So I feel like giving the user more power to outright replace what they like using our framework is better.
> > 
> > 
> > I see the point. People will do it if they really want to. Maybe we could do something like the `--i-am-really-sure` flag we have in the nomad cli? Something which you actively need to add, instead of maybe accidentally hitting `y` out of habit?
> 
> I'm on board with that. Do we make it work just like Nomad where the user has to run the program again with this flag or do we let the user type in "I am really sure!". Note I capitalized the "I" and added an exclamation mark there to make for a stronger approval.

Though we want to get strong consent from users either by typing or a flag, I would say, it is still important to keep track of the old data at the same time. So that nobody can exploit this functionality for any unpleasant intention.

But, Appending new data can be considered and nice to have.

2023-09-19 12:41 UTC, sherjeelshabih commented
> > > > > I am strongly against adding an option to overwrite existent data especially if there is not a rock-solid mechanism in-place which keeps hashes and provenance of each piece of information or groupings of pieces of information.
> > > > 
> > > > 
> > > > I understand. But the problem is if a user wants to replace this, do we block them from doing so and ignore the replacing keys for now? So no asking (y/n) and just warning them about it?
> > > > They could always go around our code and replace anything they like. in the h5 files. So I feel like giving the user more power to outright replace what they like using our framework is better.
> > > 
> > > 
> > > I see the point. People will do it if they really want to. Maybe we could do something like the `--i-am-really-sure` flag we have in the nomad cli? Something which you actively need to add, instead of maybe accidentally hitting `y` out of habit?
> > 
> > 
> > I'm on board with that. Do we make it work just like Nomad where the user has to run the program again with this flag or do we let the user type in "I am really sure!". Note I capitalized the "I" and added an exclamation mark there to make for a stronger approval.
> 
> Though we want to get strong consent from users either by typing or a flag, I would say, it is still important to keep track of the old data at the same time. So that nobody can exploit this functionality for any unpleasant intention.
> 
> But, Appending new data can be considered and nice to have.

The issue is we cannot prevent anyone from doing anything nefarious. It will be good to provide an option to keep old data. But in most cases, we will only append /nexus/paths. We will most likely never overwrite "raw" h5 data paths. Where I could see this overwrite conflict is from entries added by one of our readers. In that case, the overwrite will provide a more recent either bug fixed version of the /nexus/path in question or a more feature rich version. For example, we gain some new plot functionality and a user wants to quickly update their NXS files to gain this new feature. I want to accommodate these users and not make it a hassle for them in the name of trying to prevent nefarious acts. Those folks will find an even simpler way to manipulate the data.

We can, in the future, provide an option to preserve old data under certain NeXus concepts with pynxtool/reader versions, etc.

2024-08-20 21:07 UTC, rettigl commented
I would find such an option very important, e.g. to add evaluation results to a file. What is the status on this?

2025-01-14 17:56 UTC, sanbrock commented
To open an existing file for adding/modifying its data one can open it in 'r+' mode. 'a' mode enables adding content to a non-existing file by automatically creating it as a new file. 
Note that the command line flag '--append' (also in its documentation) suggests that it is appending data to the file and not modifying its already contained datasets.
If we do not ensure in our implementation that the new information added to the file will not modify existing datasets/attributes, I suggest to call the new feature, '--merge' or '--update'. Otherwise, it could be '--add', or '--append'.

Note that the data converter does not know about the old file and does not check it, so cannot guarantee data consistency in it. Until know, it was the duty of the reader to guarantee that, but it only guarantees it for the content to be added/updated/merged. Any data left untouched, and their consistency (also semantic meaning) may be broken.
E.g.
**/myentry/oldprocessing** (which may stored the data processing results of the content in **/enty**) can become completely detached from an updated **/myentry**
This can lead to a complete misinterpretation. Hence, it must be stressed that the data consistency must be checked and guaranteed by the person/code running the data converter in this mode. I would probably chose an even stronger flag to reflect this (e.g. '--manipulate').

2025-01-14 18:09 UTC, sanbrock commented
A related question is about the root attributes. Their semantic meaning (e.g. file creation, or which software has produced the file, or which version of the NeXus definitions were used, etc.) should cover the whole file which is not possible in this mode since we manipulate only part of it.
A better (or at least cleaner) approach is to create separate files and link their contents. All pieces should be consistent in themselves, and whoever is linking them using a new master file shall guarantee the consistency of the new tree.

2025-01-14 18:12 UTC, sanbrock commented
Note that this approach in an RDM also solves the problem of versioning, because here, we always create a new (version of the) file, so the RDM can easily connect the different versions (e.g. using the experiment identifier).

2025-01-15 13:05 UTC, RubelMozumder commented
In this whole discussion there are pros and cons, whatever we decide to implement:
Let's not confine ourselves to a hdf5 file as a standalone object,

`merge/add (In Append mode)`:
Pros:
   1. One can add different concepts (quantities/fields, sections/groups) in a hdf5 file, disregarding what file already contains. (Cons: File will end up as a dump storage, not anymore relevant with any specific technical application definitions and version. Which is completely misleading and not suggested by nomad.) We can think it only when pynxtools is a standalone tools.
   2. Do we also want to append the value of a concept? I think, This would be a complete messed up.
  
`Overwrite (In Append mode)`:
   `Partial`
   1. This would check each existing concept in the hdf5 file without any modification. At the same time, it also add new fields/concepts. (Cons: Existing metadata and data might be absolute and irrelavent at all. Which we do not want.)
   `Full`
   1. It would overwrite existing concepts, and add new concepts, which is similar to `w` mode. 
Having `a` mode, it allows to reading and writing of file at the same time. (Cons: There also resource contention might happen. If reading and writing of a concept occurs at the same time though might be very rare.)  

We could think `Overwrite (In Append mode) Full` if it helps in nexus entry processing and writing in nomad.

2026-02-12 15:37 UTC, lukaspie commented on src/pynxtools/dataconverter/convert.py
> +        append = False
```suggestion
    append = kwargs.pop("append", False)
```
This should do the same trick (and be applied to similar checks above)

2026-02-12 16:33 UTC, mkuehbach commented on src/pynxtools/dataconverter/convert.py
> +        append = False
Suggestions taken

2026-02-26 16:26 UTC, mkuehbach commented on .github/workflows/pytest.yml
> +        python-version: ["3.11", "3.12", "3.13"]
see nomad-FAIR https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/2545

2026-02-26 16:26 UTC, mkuehbach commented on .github/workflows/pytest.yml
> +        python-version: ["3.11", "3.12", "3.13"]
and here https://github.com/FAIRmat-NFDI/pynxtools/actions/runs/22446892414/job/65003801080

2026-02-27 14:15 UTC, lukaspie requested changes
This looks already quite good.

What I don't understand from the docs: how would I call this append mode now? Both from the CLI and programatically? This should be explained.

2026-02-27 14:15 UTC, lukaspie commented on .github/workflows/pytest.yml
> +        python-version: ["3.11", "3.12", "3.13"]
Let's wait with merging than until this gets resolved (IIUC, it is being worked on right away).

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +  that is injected via software that might not be written in Python.
```suggestion
- Content within `NXentry` instances is generated by executing a specific `pynxtools` reader plugin and may be supplemented with additional data provided by external software components, including those implemented outside of Python.
```
We call these reader plugins elsewhere in the docs.

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +  that is injected via software that might not be written in Python.
Rest is just suggested language improvements for readability.

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
>  passing the `--append` flag during [command line invocation](../../tutorial/converting-data-to-nexus.md).
Let's try to use the same link format as in `nomad-docs` (see [writing guide](https://github.com/FAIRmat-NFDI/nomad-docs/blob/develop/docs/writing_guide.md?plain=1#L40)).


```suggestion
passing the `--append` flag during command line invocation (see [Tutorial -> Converting your research data to NeXus](../../tutorial/converting-data-to-nexus.md).
```

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +# Dataconverter append mode
Not sure if this should be its own page, but fine for now.

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +  Instead, users should validate [the HDF5 file](../../how-tos/pynxtools/validate-nexus-files.md) when having the file compositing completed.
Also use link format as above.

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +`NeXus_repository`, `NeXus_release`, `HDF5_Version`, `h5py_version`, `creator`, `creator_version`, `file_time` and `file_update_time`.
```suggestion
A subsequent writing to the HDF5 file in append mode does not modify these. This makes the interpretation of the following attributes ambiguous:
`NeXus_repository`, `NeXus_release`, `HDF5_Version`, `h5py_version`, `creator`, `creator_version`, `file_time` and `file_update_time`.
```

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +from at least one pynxtools tool running in append mode. Note that the absence of this flag does not guarantee that the file was written
```suggestion
from at least one `pynxtools` tool running in append mode. Note that the absence of this flag does not guarantee that the file was written
```

2026-02-27 14:15 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +the combination of the `ENTRY/definition`, `ENTRY/definition/@version`, and `/@NeXus_version` attributes.
```suggestion
Until the NeXus standard allows users to link or define these attributes at the HDF5 object level, i.e. for groups, datasets, and attributes, separately,
we advise not  to mix tools that write content that adheres to different versions of the NeXus definitions. Note that The `validate` functionality of `pynxtools` does not provide a mechanism to determine which specific NeXus or tool version was used to generate individual objects within an HDF5 file. The validation concludes from
the combination of the `ENTRY/definition`, `ENTRY/definition/@version`, and `/@NeXus_version` attributes.
```
one sentence was a bit weird to read

2026-02-27 14:15 UTC, lukaspie commented on docs/index.md
> +- [Append mode `dataconverter`](learn/pynxtools/dataconverter-append-mode.md)
```suggestion
- [Append mode for the dataconverter](learn/pynxtools/dataconverter-append-mode.md)
```

2026-02-27 19:04 UTC, mkuehbach commented
> This looks already quite good.
> 
> What I don't understand from the docs: how would I call this append mode now? Both from the CLI and programatically? This should be explained.

Examples calls added to the docs

2026-03-16 13:05 UTC, lukaspie approved these changes
LGTM, provided we change back the `pytest` workflow as it should work again.

Docs on append could be slightly cleaner (i.e., that the output file is the one that is being appended), but it's fine for now.

Thanks for the implementation!

2026-03-16 13:05 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +Taking this tutorial and its NXxps case study as an example. It composes the HDF5 file with content from two input files
```suggestion
We take this tutorial and its `NXxps` case study as an example. It composes the HDF5 file with content from two input files:
```

2026-03-16 13:05 UTC, lukaspie commented on .github/workflows/pytest.yml
> +        python-version: ["3.11", "3.12", "3.13"]
I think that should work again, correct? So let's go back to allowing 3.10 again.

2026-03-16 13:05 UTC, lukaspie commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +    output="Au_25_mbar_O2_no_align.nxs",
So basically the output file would be the one that is appended to? Can we document this a bit cleaner?

I am not sure I like this call structure, but I don't have a better option at hand.

2026-03-17 12:08 UTC, mkuehbach commented on src/pynxtools/dataconverter/convert.py
> +        Skips verification routine if set to True
should add a note that its always skipped when in append mode

2026-03-17 12:08 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +  that is injected via software that might not be written in Python.
Suggestion taken

2026-03-17 12:08 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
>  passing the `--append` flag during [command line invocation](../../tutorial/converting-data-to-nexus.md).
Second suggestion taken.

2026-03-17 12:08 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +  Instead, users should validate [the HDF5 file](../../how-tos/pynxtools/validate-nexus-files.md) when having the file compositing completed.
Done

2026-03-17 12:08 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +`NeXus_repository`, `NeXus_release`, `HDF5_Version`, `h5py_version`, `creator`, `creator_version`, `file_time` and `file_update_time`.
Fixed

2026-03-17 12:08 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +from at least one pynxtools tool running in append mode. Note that the absence of this flag does not guarantee that the file was written
Edited

2026-03-17 12:08 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +the combination of the `ENTRY/definition`, `ENTRY/definition/@version`, and `/@NeXus_version` attributes.
Suggestion taken

2026-03-17 12:08 UTC, mkuehbach commented on docs/index.md
> +- [Append mode `dataconverter`](learn/pynxtools/dataconverter-append-mode.md)
Fixed

2026-03-17 12:08 UTC, mkuehbach commented on src/pynxtools/dataconverter/convert.py
> +        Skips verification routine if set to True
Added

2026-03-17 12:08 UTC, mkuehbach commented on .github/workflows/pytest.yml
> +        python-version: ["3.11", "3.12", "3.13"]
Reactivated it

2026-03-17 12:10 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +Taking this tutorial and its NXxps case study as an example. It composes the HDF5 file with content from two input files
Edited

2026-03-17 12:14 UTC, mkuehbach commented on docs/learn/pynxtools/dataconverter-append-mode.md
> +    output="Au_25_mbar_O2_no_align.nxs",
Edited

2026-03-17 12:30 UTC, merged