Updates ASE package in pyproject.toml
FAIRmat-NFDI/pynxtools pull request #263
Opened 2024-02-26 10:03 UTC by sherjeelshabih

Nomad wants to update the ASE package now. This is to help build the dependency file in the Nomad repo and to merge when everything there works.

- [ ] Check if this branch still works with the updated Nomad branch

2024-02-26 13:02 UTC, sherjeelshabih commented
The error we see here would most likely be gone with @mkuehbach's changes for EM and APT. We can wait for the relevant PRs to be merged or we can disable the imports temporarily, if there is an urgency from @ladinesa.

2024-02-26 13:08 UTC, mkuehbach requested changes

2024-02-26 13:08 UTC, mkuehbach commented on pyproject.toml
The issue is related to the fact that the ifes library was heavily refactored and updated, given that >=0.0.9 it will pull since today the newest version, with function names that are no longer the same as they are by the still not updated apm reader. My proposal is:
set ifes_apt_tc_data_modeling==0.0.9 and merge this, then the parsers will still work as they are as both refactorings for em and apm have not yet been merged.

The merge will bump ifes_apt_tc_data_modeling
Immediately after the merge 
The em and apm readers will be made into plugins and with this all remaining em_* readers and the apm reader in the pynxtools main repo and with this also the ifes dependency will be removed

2024-02-26 13:11 UTC, sherjeelshabih commented on pyproject.toml
Thank you. This helps. I'll switch to ==0.0.9 and let the CI do the testing.

2024-02-26 13:16 UTC, sherjeelshabih commented on pyproject.toml
I guess now ifes_apt_... at 0.0.9 is limited to Python3.11.  Let me ask Alvin how quick he needs this resolved.

2024-02-26 13:21 UTC, mkuehbach commented on pyproject.toml
Wait I recall this was an issue some time ago lemme check the version history I think there is also one for 3.12

2024-02-26 13:23 UTC, sherjeelshabih commented on pyproject.toml
Alright. Thanks. Also, Alvin says this can wait. So no rush.

2024-02-26 13:26 UTC, mkuehbach commented on pyproject.toml
v0.1 released that constraint and was used at the time I think by @domna in a deployment,
so use ==0.1 refactoring function names was done after that release

2024-02-26 13:58 UTC, sherjeelshabih commented
Before this gets merged we should check we can install this with Nomad.

2024-03-05 06:40 UTC, lukaspie approved these changes
NOMAD CI passes as far as I can see, so this should be good to go.

2024-03-11 11:05 UTC, lukaspie commented
Could you update the Nomad MR (https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/1700) to the latest commit in this PR here before merging here? Just to see that the installation still works.

2024-03-11 11:12 UTC, mkuehbach approved these changes
For now setting ifes==0.1 hard is okay, so this PR is LGTM to me.
With the pynxtools-apm plugin addition we have to go to >=0.2...

2024-03-11 11:26 UTC, merged