Validation based on hdf tree traversal
FAIRmat-NFDI/pynxtools pull request #333
Opened 2024-05-17 10:30 UTC by domna

This is a sketch of a hdf tree traversal by the rough ideas I already had in my head I didn't want to forget during my holidays. With the additional functions I added during the development #323 this easily checks for all the elements in the whole tree dynamically. Mainly it misses the actual checking routines for fields and attributes. Generally, it seems it's much more straightforward than the verification in the dict, because we have much less specialities we need to consider. However, it could be that the performance is not as good, because we traverse the hdf each time. But I tried to build a cached recursive function to balance that off.

This can be used as a proper basis for #133.

2024-08-12 09:08 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +            # NX_TRANSFORMATIONS is a pseudo unit
I am confused in l:682, the unit is enveloped by square parenthesis. Because the categories are expected to be string.

2025-08-11 09:49 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> -        Returns:
We don't actually need to return here as we generate all the logging warning within the function anyway.

2025-08-11 09:50 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> +    # check_attributes_of_nonexisting_field(tree)
See https://github.com/FAIRmat-NFDI/pynxtools/pull/691

2025-08-13 08:55 UTC, RubelMozumder commented on src/pynxtools/dataconverter/convert.py
> +        If True, all undocumented items are ignored in the validation.
Logic (according to the docs) has been flipped; no corresponding changes around.

2025-08-13 09:23 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +        if nxdl_f_path is None:
We can use the existing code used in [definition/dev_tools](https://github.com/FAIRmat-NFDI/nexus_definitions/blob/b4acce96a000268251848b5a68e0e4b977574157/dev_tools/utils/nxdl_utils.py#L437)

2025-08-13 09:32 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +        value = value[0]
only considering tuple of len()==1, what is the case if it is len()>1

2025-08-13 09:39 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +            if enum_value not in nxdl_enum:
Does oder matter in the enum_value? So, if `enum_value` has different exist in nxdl_enum but in different order, it can not handle.

2025-08-13 09:40 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +    - Otherwise, return it unchanged.
```suggestion
    - Otherwise, return it unchanged.
```

2025-08-13 09:42 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +    return attr
```suggestion
    if isinstance(attr, bytes):
        return attr.decode(encoding)
    return attr
```

2025-08-13 10:02 UTC, RubelMozumder commented on src/pynxtools/dataconverter/nexus_tree.py
> +            search_tags = f"*[self::nx:{node_type}{tag_type}]"
```suggestion
            search_tags = rf"*[self::nx:{node_type}{tag_type}]"
```

2025-08-13 10:03 UTC, RubelMozumder commented on src/pynxtools/dataconverter/nexus_tree.py
> +            search_tags = f"*[self::nx:{node_type}{tag_type}]"
So, search_tags is always raw.

2025-08-13 10:05 UTC, RubelMozumder commented on src/pynxtools/dataconverter/nexus_tree.py
> +            "optional": ("optional", "recommended", "required"),
We can define it at the object level rather than here and require_fields_attributes.

2025-08-13 10:28 UTC, RubelMozumder commented on src/pynxtools/testing/nexus_conversion.py
> +
I am not sure why it is here. We already have the data template via the `convert` function. It will unnecessarily double the test time.

2025-08-13 10:34 UTC, lukaspie commented on src/pynxtools/testing/nexus_conversion.py
> +
It is mostly there so that we can check that the file validation functionality does not break anything for the readers when we run the plugin tests from the pynxtools CI/CD. Template and file validation have subtle difference (just because of how the template works). I would like to keep this here, at least while the HDF5 validation is still new.

Test time will not be doubled btw, the file validation is much faster than e.g. the `read_nexus` tool (which takes 90% of test time).

2025-08-13 10:36 UTC, lukaspie commented on src/pynxtools/dataconverter/convert.py
> +        If True, all undocumented items are ignored in the validation.
We already allow only `ignore_undocumented` as a key, the old docs were just outdated. So can be considered a drive-by fix

2025-08-13 10:38 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +            if enum_value not in nxdl_enum:
I don't understand this comment, sorry. Can you please reformulate?

2025-08-13 10:41 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +    return attr
Yeah, that makes sense. I was originally considering to do something more with this function, but as it stands, can be simplified.

2025-08-13 10:50 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +        if nxdl_f_path is None:
Okay, implemented

2025-08-13 10:56 UTC, lukaspie commented on src/pynxtools/dataconverter/nexus_tree.py
> +            "optional": ("optional", "recommended", "required"),
Ok, done

2025-08-13 11:00 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +        value = value[0]
In h5py, you sometimes get something like: `value = (42,)`. If we leave it as a tuple and pass it through the next step (conversion to np array), you get `array([42])`, which is not a scalar — it’s a 1-element array. This is what we avoid here.

However, if you have a tuple of length > 1 (e.g. `(1, 2, 3)`), we _don't_ want to unwrap first before passing it to the np.array call. So we just leave it as is.

2025-08-13 11:03 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +            # NX_TRANSFORMATIONS is a pseudo unit
This is old code that does not exist anymore, are you sure you were on the latest diff? Anyway, doesn't matter as this code was removed.

2025-08-14 07:25 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +        value = value[0]
Yeah, then we can remove lines 713 and 714, right? Because, we are checking the type of the element of tuple, it does not matter how many elements it contains.

2025-08-14 07:25 UTC, RubelMozumder commented on docs/learn/pynxtools/nexus-validation.md
> +This CLI tool can be used to validate _existing_ HDF5 files that claim to be NeXus-compliant. Read more in the [API documentation](reference/cli-api.md#validate_nexus).
`validate_nexus` does not test but verifies a given nexus file against the nexus application definition.

2025-08-14 07:35 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +        value = value[0]
No, we can't. We _do_ want to convert the tuple if it is of length 1 because of my argument above: `value = (42,)` would be invalid if we don't convert.

2025-08-14 07:36 UTC, lukaspie commented on docs/learn/pynxtools/nexus-validation.md
> +This CLI tool can be used to validate _existing_ HDF5 files that claim to be NeXus-compliant. Read more in the [API documentation](reference/cli-api.md#validate_nexus).
Yes, that's right. I changed it. Will anyway have to update the documentation a bit.

2025-08-14 09:27 UTC, RubelMozumder requested changes
Currently, I found a few warning for NXmpes
´´´
WARNING: A link was used for /entry/sample/bias_env/voltmeter, but no '@target' attribute was found.
WARNING: A link was used for /entry/sample/gas_pressure_env/pressure_gauge, but no '@target' attribute was found.
WARNING: A link was used for /entry/sample/temperature_env/temperature_sensor, but no '@target' attribute was found.
```
IMO, Which should not be warning because they are recommended field.

Also, some unit warning in xps example.
```
The unit /1_as_loaded__Survey/instrument/electronanalyzer/detector/raw_data/raw/@units = counts has no documentation.
The unit /1_as_loaded__Survey/instrument/electronanalyzer/detector/raw_data/cycle0_scan0/@units = counts has no documentation.
```
Regarding spm, I will skip the validation. As application definition will be restructured very soon.

2025-08-14 09:27 UTC, RubelMozumder commented on src/pynxtools/dataconverter/validate_file.py
> +from os import path
Probably this is an unintentional import (os twice).

2025-08-14 09:27 UTC, RubelMozumder commented on src/pynxtools/dataconverter/validation.py
> -        Returns:
If this is the case, we do not need this function anymore. This function does not get any pointer where it may update/append/delete data. Until now this function returns the bool as a result of the prefix checking.

2025-08-14 10:59 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> -        Returns:
Of course we still need the function. It checks the reserved prefixes and logs a warning if one of them is used in the wrong context. We want to keep that functionality. The function however does not need to return as we don't do anything with this return value afterwards.

2025-08-14 11:01 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> +    # check_attributes_of_nonexisting_field(tree)
Removed as part of #691

2025-08-14 11:15 UTC, lukaspie commented
> Currently, I found a few warning for NXmpes
> 
> ```
> WARNING: A link was used for /entry/sample/bias_env/voltmeter, but no '@target' attribute was found.
> WARNING: A link was used for /entry/sample/gas_pressure_env/pressure_gauge, but no '@target' attribute was found.
> WARNING: A link was used for /entry/sample/temperature_env/temperature_sensor, but no '@target' attribute was found.
> ```
> 
> IMO, which should not be a warning because they are recommended fields. But it is not a problem if it does not affect our test.

One _should_ write the target attribute when one uses a link, so it is reasonable to give a warning if it is not given in the file. Note that for the template validation, if `@target` is not present, we add it automatically.

For the tests that produce this warning, we should just regenerate the test files.

> Also, some unit warning in xps example. Though units are there in the nexus file. Probably the reason you have not used the unit registry from pynxtools.
> 
> ```
> The unit /1_as_loaded__Survey/instrument/electronanalyzer/detector/raw_data/raw/@units = counts has no documentation.
> The unit /1_as_loaded__Survey/instrument/electronanalyzer/detector/raw_data/cycle0_scan0/@units = counts has no documentation.
> ```

These are somewhat expected because `NXdata/AXISNAME` [does not have any units attached](https://github.com/FAIRmat-NFDI/nexus_definitions/blob/fairmat/base_classes/NXdata.nxdl.xml#L336). So the units actually are undocumented, so the log messages are expected.

2025-08-14 11:21 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +        value = value[0]
If the tuple has more than one values, we convert tuple to numpy array. We can also do it for single element tuple as well. I just played a bit around:
```
In [13]: tu = (5,)

In [14]: tu1 = (5,5)

In [15]: np.array(tu)
Out[15]: array([5])

In [16]: np.array(tu1)
Out[16]: array([5, 5])
```
End of the function, we check if datatype of the numpy array belongs to the accepted datatype. Right?

2025-08-14 11:26 UTC, RubelMozumder commented on src/pynxtools/dataconverter/helpers.py
> +            if enum_value not in nxdl_enum:
I mean if enum_value = [1,2], then `enum_value in nxdl_enum` is true but `[2,1] in nxdl_enum` is false,

2025-08-14 11:29 UTC, RubelMozumder commented on src/pynxtools/testing/nexus_conversion.py
> +
Yeah, we can keep it. I am just wondering if it has a big impact on the test run.

2025-08-14 11:54 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +            if enum_value not in nxdl_enum:
Yes, it has to be in that exact order

2025-08-14 12:59 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +        value = value[0]
Now that I think about it, I think the use case for this was something related to tuple of bytes (e.g. `((b"Name",),)`).
But this probably does not occur too often. I'll just remove it.

2025-08-14 15:06 UTC, lukaspie commented on src/pynxtools/dataconverter/validate_file.py
> +from os import path
Thanks, I removed one of the imports

2025-08-14 15:36 UTC, lukaspie commented
> Regarding SPM, I will skip the validation. The application definition will be restructured very soon.

I think in this particular case you do not need to change anything in pynxtools-spm, but it would be great if you could just regenerate the files once again. As you can see [here](https://github.com/FAIRmat-NFDI/pynxtools/actions/runs/16969273029/job/48102741148?pr=333), the tests only fail because we are now automaticall writing a `@target` attribute whenever links is used and therefore the logs are different. Would be great if you could simply update all SPM files accordingly, so that all tests pass here.

2025-08-14 15:36 UTC, lukaspie commented
> Regarding SPM, I will skip the validation. The application definition will be restructured very soon.

I think in this particular case you do not need to change anything in pynxtools-spm, but it would be great if you could just regenerate the files once again. As you can see [here](https://github.com/FAIRmat-NFDI/pynxtools/actions/runs/16969273029/job/48102741148?pr=333), the tests only fail because we are now automaticall writing a `@target` attribute whenever links is used and therefore the logs are different. @RubelMozumder Would be great if you could simply update all SPM files accordingly, so that all tests pass here.

2025-08-14 21:21 UTC, RubelMozumder approved these changes
LGTM! 
As you mentioned, I created the test files that work fine. 
But, the test are only passing for `hdf-based-validation` branch. So, you can merge it, I have created [PR](https://github.com/FAIRmat-NFDI/pynxtools-spm/pull/43) rearding prepared for this PR.

2025-08-15 08:30 UTC, rettigl requested changes
This introduces a lot new code, where some of it, in particular in validation.py seem to be sometimes duplicates from existing code. This will make future maintenance rather difficult. Is it possible to move common code to a different place and reuse?

Also, while playing around, I recognized some errors which are not recognized:
This wrong dict:
```
  "/ENTRY/CALIBRATION[energy_referencing]":{
    "calibrated_axis": "@link:/entry/data",
    "calibrated_axis/@units": "eV",
    "physical_quantity": "energy",
    "reference_peak": "@attrs:metadata/scan_info/reference_energy",
    "binding_energy": 0.0,
    "binding_energy/@units": "eV"
  },
```
Generates the error
`ERROR: Expected a field at /ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis, but found a group.`
during validation, but the link is still being set, and this a units attribute is being written to /entry/data. This is not being picked up neither by the converter nor the validator. The wrong type of /entry/energy_referencing/calibrated_axis is neither reported by the validator.

2025-08-15 08:30 UTC, rettigl commented on dev-requirements.txt
> +tzdata==2024.1
Why this downgrade?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/helpers.py
> +        return value.astype(float)
What is this case for? I believe it could raise an attribute error for some cases (?)

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/helpers.py
> +        value = list(value)
Not sure I understand this case here

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/testing/nexus_conversion.py
> +
I also like this and find it important. This provides another level of consistency check for both the readers, datamodels, and our validation tools.

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/helpers.py
> +            if enum_value not in nxdl_enum:
I think the question is if ["A", "C", "B"] should be a valid item of an enumeration [["A", "B", "C"], ["D", "E", "F"]]. I would say no, because order matters, e.g. in enumerations for axes.

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/helpers.py
> -
I don't understand this part, is this still relevant as todo?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/nexus_tree.py
> +    # TODO rename type to nx_type in every place
maybe still do in this PR?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/nexus_tree.py
> +            or self.inheritance[0].attrib.get("minOccurs") == "0"
Shouldn't this minOccurs become the lower occurence_limit? Why both checks?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validate_file.py
> +                )
Maybe this should be a warning?

2025-08-15 08:30 UTC, rettigl commented on tests/dataconverter/test_validation.py
I did not check everything here, but looks okay to me

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> -def best_namefit_of(
Why did you move this? Makes review a bit difficult.

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> -def best_namefit_of(
But maybe sorts functions more logically, okay.

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +                    #     raise TypeError("Expected group for {path}")
Not sure I understand correctly. Does this mean, currently we don't check if a link target corresponds to the right type? Could this not break file writing?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +    def check_reserved_suffix(path: str, parent_data: h5py.Group):
I don't understand why this shows up as new code, was this not there since a long time?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +    def check_reserved_suffix(path: str, parent_data: h5py.Group):
Ah, it seems a lot of functions are there now in two flavors, once in validate_hdf... and once in validate_dict...
Does this not make the code very hard to maintain? Could we reuse common code lines?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +                keys[variant],
Why this change?

2025-08-15 08:30 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
I also did not check all new code here. Some of it seems more or less duplicated from code we have elsewhere. This seems to be a potential problem for future maintenance.

2025-08-15 08:31 UTC, rettigl commented on src/pynxtools/dataconverter/helpers.py
> +        return value.astype(float)
Probably outdated.

2025-08-15 08:42 UTC, lukaspie commented on src/pynxtools/dataconverter/validate_file.py
> +                )
We could, but then we would need to have it in every single test with a warning as well. Or we just ignore any message that starts with "Invalid" in the tests, that's probably fine .

2025-08-15 08:47 UTC, lukaspie commented on src/pynxtools/dataconverter/validate_file.py
> +                )
I implemented a warning now which is ignored in the failing tests (so we don't have to add it everywhere).

2025-08-15 08:48 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> -def best_namefit_of(
We now have two separate functions called `best_namefit_of`, each as an inner function to the two different validation methods. Therefore, I had to move the whole function.

2025-08-15 08:54 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> +    def check_reserved_suffix(path: str, parent_data: h5py.Group):
The problem is that these actually have to perform slightly differently depending on whether we do HDF5 or template validation. So I basically build two similar functions as inner functions to the two big validation functions. 

We could probably move the actual checking of prefixes against instance names to a separate function, but that does not help too much (we'd still need two wrappers around that checking  function for the two use cases).

**EDIT**: see below, prefix checking is only one function now. The rest is fairly unique for either of the two cases.

2025-08-15 08:55 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> +                keys[variant],
It is a bit more efficient, before we were getting the value from the whole mapping table, but we have a subset of the mapping available here that we can directly access.

2025-08-15 09:12 UTC, lukaspie commented on src/pynxtools/dataconverter/nexus_tree.py
> +    # TODO rename type to nx_type in every place
Done! This introduces a larger diff though (also on the `eln_mapper`), but we have enough tests to check that I didn't miss any occurence.

2025-08-15 09:16 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> +        return value.astype(float)
Has to be used because `h5py` returns numpy arrays numeric datasets (integers, floats) and we want to convert those as well. I didn't see any issues with attribute errors so far, but I for sure haven't tested _everything_.

I think the larger issues is that maybe it is actually not desirable to always convert ints to floats. I know you wanted to have this to make it easier to write valid files, but there may be some cases where conversion is not possible and there is also a precision loss when converting int to float.

Maybe we could eventually get rid of it and rather provide a simple conversion directly from the config file (see https://github.com/FAIRmat-NFDI/pynxtools/pull/524).

2025-08-15 09:18 UTC, lukaspie commented on dev-requirements.txt
> +tzdata==2024.1
Not sure where that came from. I ran `uv compile` again with `--upgrade-package tzdata` and it did not complain, so it is fine to revert this change

2025-08-15 09:20 UTC, lukaspie commented on src/pynxtools/dataconverter/helpers.py
> -
No, turns out it is not needed as we internally don't allow compressing booleans/strings in the writer. This was a leftover from #686 that can now be safely removed.

2025-08-15 09:23 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
As I said above, it is very hard to disentangle the actual validity checks (e.g. for suffixes, prefixes) and namefitting from the way that the data is structured in the template or the HDF group. 

I managed to use only one function for suffixes/prefixes now with small wrappers around it for both use cases, that should minimize maintenance a bit.

2025-08-15 09:56 UTC, lukaspie commented on src/pynxtools/dataconverter/nexus_tree.py
> +            or self.inheritance[0].attrib.get("minOccurs") == "0"
You can write both `minOccurs=0` or `optional=True` in the NeXus definitions, it is a bit redundant as both tell you that the concept is optional. We are just checking either/or here.

2025-08-15 09:58 UTC, lukaspie commented
`pynxtools-spm` tests are still failing, but they work with https://github.com/FAIRmat-NFDI/pynxtools-spm/pull/43

2025-08-15 10:02 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> +                    #     raise TypeError("Expected group for {path}")
We only run this check when validating existing files, so this does not affect file writing.

I initially had checks where I linked a field to a group and vice-versa. Turns out this breaks the writing (because then it writes nonsense like `NX_class=NX_FLOAT`. This would however be caught by the template validator. For existing files, this should never occur. So basically, this was a particularity of our testing just because in tests, we write the template to file without validating. So it is safe to say that this doesn't actually happen outside the tests, so it is fine to remove this part here.

2025-08-15 11:35 UTC, RubelMozumder commented
> `pynxtools-spm` tests are still failing, but they work with [FAIRmat-NFDI/pynxtools-spm#43](https://github.com/FAIRmat-NFDI/pynxtools-spm/pull/43)

That PR was prepared for the branch `hdf-base-validation`. If you merge this PR to the master branch, I can merge that PR as well. Later, you can release a patch version for pynxtools.

2025-08-18 08:33 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
The checking of suffixes is now also just one function that both validators call.

2025-08-18 08:34 UTC, lukaspie commented on src/pynxtools/dataconverter/validation.py
> +    def check_reserved_suffix(path: str, parent_data: h5py.Group):
EDIT: The checking of suffixes is now also just one function that both validators call. We don't actually need to have a complicated wrapper logic, we can just do everything in one go.

2025-08-19 15:24 UTC, lukaspie commented
> Also, while playing around, I recognized some errors which are not recognized: This wrong dict:
> 
> ```
>   "/ENTRY/CALIBRATION[energy_referencing]":{
>     "calibrated_axis": "@link:/entry/data",
>     "calibrated_axis/@units": "eV",
>     "physical_quantity": "energy",
>     "reference_peak": "@attrs:metadata/scan_info/reference_energy",
>     "binding_energy": 0.0,
>     "binding_energy/@units": "eV"
>   },
> ```
> 
> Generates the error `ERROR: Expected a field at /ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis, but found a group.` during validation, but the link is still being set, and this a units attribute is being written to /entry/data. This is not being picked up neither by the converter nor the validator. The wrong type of /entry/energy_referencing/calibrated_axis is neither reported by the validator.

Indeed, in #642  (specifically in commit https://github.com/FAIRmat-NFDI/pynxtools/commit/5941b1f1416109d13a4972d910202c124c512341), we decided that such keys shall not be removed, even if they are erroneous. I think this was the wrong decision then and we should remove such keys in order to still produce a valid file. I have implemented with [`28371b0`](https://github.com/FAIRmat-NFDI/pynxtools/pull/333/commits/28371b0dab59301f509152cc70677e37447d6158) and  [`372a879`](https://github.com/FAIRmat-NFDI/pynxtools/pull/333/commits/372a87961ce2fe8ef8b31b5125ff7864ca0aaa9b) now that such keys that are linked to the wrong NeXus type are removed. In order not to create nonsense in the file, we also need to remove any further subkeys (e.g., additional attributes for fields)

Here's the result for your example:
```
"/ENTRY/CALIBRATION[energy_referencing]":{
  "calibrated_axis": "@link:/entry/data",
  "calibrated_axis/@units": "eV",
  "physical_quantity": "energy",
  "reference_peak": "@attrs:metadata/scan_info/reference_energy",
  "binding_energy": 0.0,
  "binding_energy/@units": "eV"
},
```
```
ERROR: The type ('group') of '/ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis' conflicts with the concept /ENTRY/energy_referencing/calibrated_axis, which is of type 'field'.
ERROR: Expected a field at /ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis, but found a group.
WARNING: The group /ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis will not be written.
WARNING: The attribute /ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis/@units will not be written.
WARNING: The attribute /ENTRY[entry]/CALIBRATION[energy_referencing]/calibrated_axis/@target will not be written.
```

And for the other way around
```
"/ENTRY/CALIBRATION[energy_referencing]":"@link:/entry/data/energy",
```
```
ERROR: The type ('field') of '/ENTRY[entry]/CALIBRATION[energy_referencing]' conflicts with the concept /ENTRY/energy_referencing, which is of type 'group'.
ERROR: Expected a group at /ENTRY[entry]/CALIBRATION[energy_referencing], but found a field or attribute.
WARNING: The field /ENTRY[entry]/CALIBRATION[energy_referencing] will not be written.
WARNING: The attribute /ENTRY[entry]/CALIBRATION[energy_referencing]/@target will not be written.
ERROR: The type ('field') of '/ENTRY[entry]/CALIBRATION[energy_referencing]' conflicts with the concept /ENTRY/CALIBRATION, which is of type 'group'.
```

Note that in the latter case, we actually find two different conflicts (with the named group `energy_referencing(NXcalibration)` as well as with the unnamed `(NXcalibration)`.

I think this should work nicely and also in the resulting files there's no confusion anymore.

2025-08-20 18:43 UTC, rettigl commented on src/pynxtools/dataconverter/helpers.py
> +        return value.astype(float)
That would off course be great, yes. However, in cases where the data type enforces float, conversion should always be possible, and precission loss not an issue, and we do the conversion only in these cases.

2025-08-20 18:44 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> -def best_namefit_of(
yes, sorry.

2025-08-20 18:44 UTC, rettigl commented on src/pynxtools/dataconverter/nexus_tree.py
> +            or self.inheritance[0].attrib.get("minOccurs") == "0"
ok

2025-08-20 18:45 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +                    #     raise TypeError("Expected group for {path}")
ok

2025-08-20 18:45 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +    def check_reserved_suffix(path: str, parent_data: h5py.Group):
great

2025-08-20 18:46 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
> +                keys[variant],
It just appeared somewhat inconsistent with the use if mapping[variant_path] further below. But if it contains the same, fine for me.

2025-08-20 18:47 UTC, rettigl commented on src/pynxtools/dataconverter/validation.py
great.

2025-08-21 08:53 UTC, merged