Add docs for CLI API
FAIRmat-NFDI/pynxtools pull request #411
Opened 2024-08-23 15:00 UTC by lukaspie

This renders like this in the docs:
![image](https://github.com/user-attachments/assets/a56a7071-2c95-4e8d-8f30-533e9e0ef60f)

2024-08-24 13:48 UTC, mkuehbach commented on src/pynxtools/dataconverter/convert.py
> +    "Prints a list of all installed readers."
"""docstring"""

2024-08-26 07:22 UTC, mkuehbach requested changes
I would add one more docstring, otherwise good work

2024-08-26 07:25 UTC, lukaspie commented on docs/index.md
> +`pynxtools` has a number of command line tools that can be used to, among others, convert data and verify NeXus file. You can more information about the
changed

2024-08-26 07:25 UTC, lukaspie commented on src/pynxtools/dataconverter/convert.py
> +    "Prints a list of all installed readers."
implemented

2024-08-26 07:30 UTC, mkuehbach approved these changes

2024-08-26 07:33 UTC, merged