using readonly instead of user_editability; enabling injesting multip…
FAIRmat-NFDI/pynxtools pull request #486
Opened 2024-12-16 19:07 UTC by sanbrock

…le methods to the base classes and not only the normalization; Entry to inherit also from Task, so Workflow click drives there directly

2024-12-19 12:02 UTC, lukaspie requested changes
We should definitely also think how we can keep this clean and maintainable in the future. Maybe we can separate the actual schema creation a bit from the definition of new base section classes and normalization functions (i.e, move these to a new python file in the future)

2024-12-19 12:02 UTC, lukaspie commented on src/pynxtools/nomad/schema.py
> +    "NXentry": [ActivityStep],  # , Task],
This should eventually becomes its own workflow (nested in the workflow of the whole nxs file) containing its own Tasks. But fine for now

2025-01-08 16:20 UTC, sanbrock commented on src/pynxtools/nomad/schema.py
> +            if hasattr(task, "name") and hasattr(task.section, "section")
Task-s registered in archive.workflow2.tasks have both 'name' and 'section' defined. It is not a problem if they are None. In fact, we need also None-s be listed in such case.

2025-01-08 16:20 UTC, sanbrock commented on src/pynxtools/nomad/schema.py
> +            if hasattr(link, "name") and hasattr(link.section, "section")
same applies here

2025-01-08 16:20 UTC, sanbrock commented on src/pynxtools/nomad/schema.py
> +            if hasattr(link, "name") and hasattr(link.section, "section")
and here

2025-01-08 16:48 UTC, RubelMozumder commented on src/pynxtools/nomad/schema.py
> +            if hasattr(task, "name") and hasattr(task.section, "section")
Initially, I got attribute errors. Later investigating the issue I see it was a bit older nomad develop branch.

2025-01-08 17:21 UTC, merged